FROM node:18.10.0 as builder

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
COPY ./packages/website/package.json ./packages/website/
COPY ./packages/api/package.json ./packages/api/
RUN yarn --frozen-lockfile
RUN yarn global add serve

# Copy source code
COPY ./packages/website ./packages/website/

ARG VITE_API_URL

# Build project
RUN cd /app/packages/website && yarn build
