version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-website
    container_name: vreal-soft-test-frontend
    command: serve -s ./packages/website/dist -l 5173
    restart: always
    ports:
      - 5173:5173
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - vreal-soft-test-network

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: vreal-soft-test-api
    restart: always
    links:
      - api_db
    environment:
      - DATABASE_URL=postgresql://vreal-soft-test:12345678@api_db:5432/vreal-soft-test
      - JWT_SECRET_KEY=secret
      - GOOGLE_CLIENT_ID=455056359211-aqgtge9r1oo3c4ol592vnc1mch9pe614.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET_KEY=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
      - GOOGLE_CLIENT_REDIRECT_URL=http://localhost:3000/google/redirect
      - CLIENT_URL=http://localhost:5173
    ports:
      - 3000:3000
    networks:
      - vreal-soft-test-network

  api_db:
    image: postgres:12.2
    volumes:
      - vreal-soft-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=vreal-soft-test
      - POSTGRES_DB=vreal-soft-test
      - POSTGRES_PASSWORD=12345678
    container_name: vreal-soft-test-api-db
    networks:
      - vreal-soft-test-network

volumes:
  vreal-soft-db:

networks:
  vreal-soft-test-network:
    driver: bridge
